// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7gWBf1rYOm1WuiAZPmNBQDsY1OszTHrw',
    appId: '1:1029519540602:web:9753346c1dc5dc93e696c3',
    messagingSenderId: '1029519540602',
    projectId: 'smart-care-hub-7aa4b',
    authDomain: 'smart-care-hub-7aa4b.firebaseapp.com',
    databaseURL: 'https://smart-care-hub-7aa4b-default-rtdb.firebaseio.com',
    storageBucket: 'smart-care-hub-7aa4b.firebasestorage.app',
    measurementId: 'G-RQ9M6M55YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu0fGd0is5vKhNU9E1oihwcK2n3ovWYbA',
    appId: '1:1029519540602:android:34cd181fabf6235be696c3',
    messagingSenderId: '1029519540602',
    projectId: 'smart-care-hub-7aa4b',
    databaseURL: 'https://smart-care-hub-7aa4b-default-rtdb.firebaseio.com',
    storageBucket: 'smart-care-hub-7aa4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA5lR26UU8cuZflrqGBOZXH831rVB_VNk',
    appId: '1:1029519540602:ios:dd6b95e2583cc4f1e696c3',
    messagingSenderId: '1029519540602',
    projectId: 'smart-care-hub-7aa4b',
    databaseURL: 'https://smart-care-hub-7aa4b-default-rtdb.firebaseio.com',
    storageBucket: 'smart-care-hub-7aa4b.firebasestorage.app',
    iosBundleId: 'com.example.smartCareHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA5lR26UU8cuZflrqGBOZXH831rVB_VNk',
    appId: '1:1029519540602:ios:dd6b95e2583cc4f1e696c3',
    messagingSenderId: '1029519540602',
    projectId: 'smart-care-hub-7aa4b',
    databaseURL: 'https://smart-care-hub-7aa4b-default-rtdb.firebaseio.com',
    storageBucket: 'smart-care-hub-7aa4b.firebasestorage.app',
    iosBundleId: 'com.example.smartCareHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7gWBf1rYOm1WuiAZPmNBQDsY1OszTHrw',
    appId: '1:1029519540602:web:5e8e79eba41757afe696c3',
    messagingSenderId: '1029519540602',
    projectId: 'smart-care-hub-7aa4b',
    authDomain: 'smart-care-hub-7aa4b.firebaseapp.com',
    databaseURL: 'https://smart-care-hub-7aa4b-default-rtdb.firebaseio.com',
    storageBucket: 'smart-care-hub-7aa4b.firebasestorage.app',
    measurementId: 'G-R11L3HNVXM',
  );

}