import 'package:flutter/material.dart';
import 'views/home_view.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'controllers/alert_controller.dart';
import 'controllers/heart_rate_controller.dart';
import 'controllers/medicine_controller.dart';
import 'firebase_options.dart'; // Generated by FlutterFire

void main() async {
  // Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const SmartCareHubApp());
}

class SmartCareHubApp extends StatelessWidget {
  const SmartCareHubApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Use MultiProvider to provide all your controllers to the widget tree
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => HeartRateController()),
        ChangeNotifierProvider(create: (_) => MedicineController()),
        ChangeNotifierProvider(create: (_) => AlertController()),
      ],
      child: MaterialApp(
        title: 'Smart Care Hub',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        home: const HomeView(),
      ),
    );
  }
}
